try{
    console.log(a);
}
catch(error){
    console.log("the code inside try didn't execute.");
    console.log(error);
}